### ISSUE TITLE
Update Ruby version

### ISSUE THREAD

**Issue by DillonB07** [gosu/ruby-app#12]
I've been porting a ruby application over to macOS using this app. However, the version of Ruby is too old. Please could you update it to 3.0? I've tried to do this manually, but I don't know how to modify the UNIX executable called `Ruby` in the `macOS` folder.

**Comment by jlnr** [comment]
I'll try to update this wrapper tomorrow. Vacation ends after this week, so if it takes longer than a couple of hours, it probably won't happen until 2023.

Sent from my iPhone

**Comment by jlnr** [comment]
Oops, that was more than two hours. Updating Ruby to version 3.0 worked. The problem is that not only does the `openssl` gem have a non-portable dependency on my homebrew folder (#8), but `yaml` and even `gosu` now reference homebrew dylibs. So the result won't be useful for pretty much anything.

You've said you are trying to port a Ruby application. Is it a Gosu game or something else? Have you tried http://foobarwidget.github.io/traveling-ruby/?

Another thing that I could try to look at for inspiration is https://github.com/Homebrew/homebrew-portable-ruby.

**Comment by jlnr** [comment]
I'll try to fix Gosu specifically here https://github.com/gosu/gosu/issues/607

OpenSSL and YAML will remain broken, and I also had to give up texplay and ashton because they won't build anymore.

**Comment by jlnr** [comment]
I've fixed the most important bug. Not sure when I'll have time to retry building the app.

Flaptus seems to use some networking code. Unless it uses unencrypted HTTP, which is on the verge of dying out, I don't think it'll work on macOS because I haven't managed to properly bundle OpenSSL into Ruby.app.

**Comment by jlnr** [comment]
Hrm, it almost works, but now there is a new dependency on libgmp.

All of these problems have been solved by the Homebrew team, and I think I (or anyone who has time for this) should try to bundle their Ruby instead of building our own version:

https://github.com/Homebrew/homebrew-portable-ruby/releases

I'll give up for now, sorry.

**Comment by jlnr** [comment]
If I'll give up on giving up in the future, things will continue here: https://github.com/gosu/ruby-app/issues/13 - feel free to subscribe.

Note that currently the portable Ruby I want to use is stuck on v2.6.8, so this won't help you if you want to run code that requires Ruby 3.
